[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
dockerfile = "frontend/Dockerfile"
directory = "frontend"

[[services]]
name = "backend"
dockerfile = "Dockerfile"
directory = "." 