[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "frontend"
dockerfile = "./Dockerfile"

[[services]]
name = "backend"
source = "."
dockerfile = "./Dockerfile" 